routers:
  hosts:
    mikrotik-hap-ax3:
      ansible_host: 192.168.88.1
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.routeros.routeros
    ansible_user: admin
    # not a real pass. ssh keys are used
    # ansible_ssh_pass: test1234
